### ISSUE TITLE
Send out events possible?

### ISSUE THREAD

**Issue by teddibaer** [metaneutrons/girf#1]
Hi Fabian,

I just stumbled over your project as I am looking (also) for smoke detectors I can connect somehow to my own home automation project.
Since you seem to have done some reverse engineering of the serial protocol - do you think there is a way to also send out an alarm so that all connected detectors start making noise (and clear the alarm later on)?

Greetings,
  Ralf

**Comment by metaneutrons** [comment]
Hi there...sorry for the late reply. It is absolutely possible to send out events. This is something I would like to implement in the future. The necessary commands are already reverse engineered (look at docs/gira_protocol_de.txt).
